import Head from "next/head";

export default function ProfilePage() {
  return (
    <>
      <Head>
        <title>Birb</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        <div>Profile view</div>
      </main>
    </>
  );
}
